chore: add ideas wrappers for all tool funcs (#4)
* chore: sync code with internal toolbox

* fix: unit tests

* chore: add ideas wrappers for all tool funcs

* fix: unit tests

* chore: update tool specs

* chore: use smaller test data

* chore: commit inputs

* chore: revert line break change

* chore: clean func signatures

* build: add separators when running all tools

I was having trouble finding out which tool was failing in the mix when using `make run-all`, so this adds cute little headers to identify which tool is being run:

```
==============================================================================
Running suite2p_individual_steps__suite2p_roi_extraction
==============================================================================

Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/tmp/ideas-toolbox-suite2p/toolbox/tools/suite2p_individual_steps.py", line 1270, in suite2p_roi_extraction_ideas_wrapper
    suite2p_roi_extraction(
  File "/tmp/ideas-toolbox-suite2p/toolbox/tools/suite2p_individual_steps.py", line 606, in suite2p_roi_extraction
    f_reg = io.BinaryFile(Ly=Ly, Lx=Lx, filename=reg_binary_file[0])
  File "/ideas/venv/lib/python3.10/site-packages/suite2p/io/binary.py", line 42, in __init__
    self.file = np.memmap(self.filename, mode=mode, dtype=self.dtype, shape=shape)
  File "/ideas/venv/lib/python3.10/site-packages/numpy/core/memmap.py", line 229, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
PermissionError: [Errno 13] Permission denied: '/tmp/data.bin'

╭──────────────────────── Failed to run tool ─────────────────────────╮
│ An error occurred running the analysis code. Check inputs and logs. │
╰─────────────────────────────────────────────────────────────────────╯
```

* chore: fix read only inputs (#8)

---------

Co-authored-by: Brandon Cazander <brandon@cazander.ca>